# Created by and for Qt Creator This file was created for editing the project sources only.
# You may attempt to use it for building too, by modifying this file here.

#TARGET = caffe

HEADERS = \
   $$PWD/include/caffe/layers/absval_layer.hpp \
   $$PWD/include/caffe/layers/accuracy_layer.hpp \
   $$PWD/include/caffe/layers/argmax_layer.hpp \
   $$PWD/include/caffe/layers/base_conv_layer.hpp \
   $$PWD/include/caffe/layers/base_data_layer.hpp \
   $$PWD/include/caffe/layers/batch_norm_layer.hpp \
   $$PWD/include/caffe/layers/batch_reindex_layer.hpp \
   $$PWD/include/caffe/layers/bias_layer.hpp \
   $$PWD/include/caffe/layers/bnll_layer.hpp \
   $$PWD/include/caffe/layers/clip_layer.hpp \
   $$PWD/include/caffe/layers/concat_layer.hpp \
   $$PWD/include/caffe/layers/contrastive_loss_layer.hpp \
   $$PWD/include/caffe/layers/conv_layer.hpp \
   $$PWD/include/caffe/layers/crop_layer.hpp \
   $$PWD/include/caffe/layers/cudnn_conv_layer.hpp \
   $$PWD/include/caffe/layers/cudnn_deconv_layer.hpp \
   $$PWD/include/caffe/layers/cudnn_lcn_layer.hpp \
   $$PWD/include/caffe/layers/cudnn_lrn_layer.hpp \
   $$PWD/include/caffe/layers/cudnn_pooling_layer.hpp \
   $$PWD/include/caffe/layers/cudnn_relu_layer.hpp \
   $$PWD/include/caffe/layers/cudnn_sigmoid_layer.hpp \
   $$PWD/include/caffe/layers/cudnn_softmax_layer.hpp \
   $$PWD/include/caffe/layers/cudnn_tanh_layer.hpp \
   $$PWD/include/caffe/layers/data_layer.hpp \
   $$PWD/include/caffe/layers/deconv_layer.hpp \
   $$PWD/include/caffe/layers/dropout_layer.hpp \
   $$PWD/include/caffe/layers/dummy_data_layer.hpp \
   $$PWD/include/caffe/layers/eltwise_layer.hpp \
   $$PWD/include/caffe/layers/elu_layer.hpp \
   $$PWD/include/caffe/layers/embed_layer.hpp \
   $$PWD/include/caffe/layers/euclidean_loss_layer.hpp \
   $$PWD/include/caffe/layers/exp_layer.hpp \
   $$PWD/include/caffe/layers/filter_layer.hpp \
   $$PWD/include/caffe/layers/flatten_layer.hpp \
   $$PWD/include/caffe/layers/hdf5_data_layer.hpp \
   $$PWD/include/caffe/layers/hdf5_output_layer.hpp \
   $$PWD/include/caffe/layers/hinge_loss_layer.hpp \
   $$PWD/include/caffe/layers/im2col_layer.hpp \
   $$PWD/include/caffe/layers/image_data_layer.hpp \
   $$PWD/include/caffe/layers/infogain_loss_layer.hpp \
   $$PWD/include/caffe/layers/inner_product_layer.hpp \
   $$PWD/include/caffe/layers/input_layer.hpp \
   $$PWD/include/caffe/layers/log_layer.hpp \
   $$PWD/include/caffe/layers/loss_layer.hpp \
   $$PWD/include/caffe/layers/lrn_layer.hpp \
   $$PWD/include/caffe/layers/lstm_layer.hpp \
   $$PWD/include/caffe/layers/memory_data_layer.hpp \
   $$PWD/include/caffe/layers/multinomial_logistic_loss_layer.hpp \
   $$PWD/include/caffe/layers/mvn_layer.hpp \
   $$PWD/include/caffe/layers/neuron_layer.hpp \
   $$PWD/include/caffe/layers/parameter_layer.hpp \
   $$PWD/include/caffe/layers/pooling_layer.hpp \
   $$PWD/include/caffe/layers/power_layer.hpp \
   $$PWD/include/caffe/layers/prelu_layer.hpp \
   $$PWD/include/caffe/layers/python_layer.hpp \
   $$PWD/include/caffe/layers/recurrent_layer.hpp \
   $$PWD/include/caffe/layers/reduction_layer.hpp \
   $$PWD/include/caffe/layers/relu_layer.hpp \
   $$PWD/include/caffe/layers/reshape_layer.hpp \
   $$PWD/include/caffe/layers/rnn_layer.hpp \
   $$PWD/include/caffe/layers/scale_layer.hpp \
   $$PWD/include/caffe/layers/sigmoid_cross_entropy_loss_layer.hpp \
   $$PWD/include/caffe/layers/sigmoid_layer.hpp \
   $$PWD/include/caffe/layers/silence_layer.hpp \
   $$PWD/include/caffe/layers/slice_layer.hpp \
   $$PWD/include/caffe/layers/softmax_layer.hpp \
   $$PWD/include/caffe/layers/softmax_loss_layer.hpp \
   $$PWD/include/caffe/layers/split_layer.hpp \
   $$PWD/include/caffe/layers/spp_layer.hpp \
   $$PWD/include/caffe/layers/swish_layer.hpp \
   $$PWD/include/caffe/layers/tanh_layer.hpp \
   $$PWD/include/caffe/layers/threshold_layer.hpp \
   $$PWD/include/caffe/layers/tile_layer.hpp \
   $$PWD/include/caffe/layers/window_data_layer.hpp \
   $$PWD/include/caffe/proto/caffe.pb.h \
   $$PWD/include/caffe/test/test_caffe_main.hpp \
   $$PWD/include/caffe/test/test_gradient_check_util.hpp \
   $$PWD/include/caffe/util/benchmark.hpp \
   $$PWD/include/caffe/util/blocking_queue.hpp \
   $$PWD/include/caffe/util/cudnn.hpp \
   $$PWD/include/caffe/util/db.hpp \
   $$PWD/include/caffe/util/db_leveldb.hpp \
   $$PWD/include/caffe/util/db_lmdb.hpp \
   $$PWD/include/caffe/util/device_alternate.hpp \
   $$PWD/include/caffe/util/format.hpp \
   $$PWD/include/caffe/util/gpu_util.cuh \
   $$PWD/include/caffe/util/hdf5.hpp \
   $$PWD/include/caffe/util/im2col.hpp \
   $$PWD/include/caffe/util/insert_splits.hpp \
   $$PWD/include/caffe/util/io.hpp \
   $$PWD/include/caffe/util/math_functions.hpp \
   $$PWD/include/caffe/util/mkl_alternate.hpp \
   $$PWD/include/caffe/util/nccl.hpp \
   $$PWD/include/caffe/util/rng.hpp \
   $$PWD/include/caffe/util/signal_handler.h \
   $$PWD/include/caffe/util/upgrade_proto.hpp \
   $$PWD/include/caffe/blob.hpp \
   $$PWD/include/caffe/caffe.hpp \
   $$PWD/include/caffe/common.hpp \
   $$PWD/include/caffe/data_transformer.hpp \
   $$PWD/include/caffe/filler.hpp \
   $$PWD/include/caffe/internal_thread.hpp \
   $$PWD/include/caffe/layer.hpp \
   $$PWD/include/caffe/layer_factory.hpp \
   $$PWD/include/caffe/net.hpp \
   $$PWD/include/caffe/parallel.hpp \
   $$PWD/include/caffe/sgd_solvers.hpp \
   $$PWD/include/caffe/solver.hpp \
   $$PWD/include/caffe/solver_factory.hpp \
   $$PWD/include/caffe/syncedmem.hpp \
   $$PWD/src/gtest/gtest.h

SOURCES = \
   $$PWD/examples/cifar10/convert_cifar_data.cpp \
   $$PWD/examples/cpp_classification/classification.cpp \
   $$PWD/examples/feature_extraction/imagenet_val.prototxt \
   $$PWD/examples/finetune_flickr_style/readme.md \
   $$PWD/examples/finetune_flickr_style/style_names.txt \
   $$PWD/examples/finetune_pascal_detection/pascal_finetune_solver.prototxt \
   $$PWD/examples/finetune_pascal_detection/pascal_finetune_trainval_test.prototxt \
   $$PWD/examples/hdf5_classification/nonlinear_auto_test.prototxt \
   $$PWD/examples/hdf5_classification/nonlinear_auto_train.prototxt \
   $$PWD/examples/hdf5_classification/nonlinear_train_val.prototxt \
   $$PWD/examples/hdf5_classification/train_val.prototxt \
   $$PWD/examples/imagenet/create_imagenet.sh \
   $$PWD/examples/imagenet/make_imagenet_mean.sh \
   $$PWD/examples/imagenet/readme.md \
   $$PWD/examples/imagenet/resume_training.sh \
   $$PWD/examples/imagenet/train_caffenet.sh \
   $$PWD/examples/mnist/convert_mnist_data.cpp \
   $$PWD/examples/mnist/create_mnist.sh \
   $$PWD/examples/mnist/lenet.prototxt \
   $$PWD/examples/mnist/lenet_adadelta_solver.prototxt \
   $$PWD/examples/mnist/lenet_auto_solver.prototxt \
   $$PWD/examples/mnist/lenet_consolidated_solver.prototxt \
   $$PWD/examples/mnist/lenet_multistep_solver.prototxt \
   $$PWD/examples/mnist/lenet_solver.prototxt \
   $$PWD/examples/mnist/lenet_solver_adam.prototxt \
   $$PWD/examples/mnist/lenet_solver_rmsprop.prototxt \
   $$PWD/examples/mnist/lenet_train_test.prototxt \
   $$PWD/examples/mnist/mnist_autoencoder.prototxt \
   $$PWD/examples/mnist/mnist_autoencoder_solver.prototxt \
   $$PWD/examples/mnist/mnist_autoencoder_solver_adadelta.prototxt \
   $$PWD/examples/mnist/mnist_autoencoder_solver_adagrad.prototxt \
   $$PWD/examples/mnist/mnist_autoencoder_solver_nesterov.prototxt \
   $$PWD/examples/mnist/readme.md \
   $$PWD/examples/mnist/train_lenet.sh \
   $$PWD/examples/mnist/train_lenet_adam.sh \
   $$PWD/examples/mnist/train_lenet_consolidated.sh \
   $$PWD/examples/mnist/train_lenet_docker.sh \
   $$PWD/examples/mnist/train_lenet_rmsprop.sh \
   $$PWD/examples/mnist/train_mnist_autoencoder.sh \
   $$PWD/examples/mnist/train_mnist_autoencoder_adadelta.sh \
   $$PWD/examples/mnist/train_mnist_autoencoder_adagrad.sh \
   $$PWD/examples/mnist/train_mnist_autoencoder_nesterov.sh \
   $$PWD/examples/net_surgery/bvlc_caffenet_full_conv.prototxt \
   $$PWD/examples/net_surgery/conv.prototxt \
   $$PWD/examples/siamese/convert_mnist_siamese_data.cpp \
   $$PWD/include/caffe/proto/caffe.pb.cc \
   $$PWD/src/caffe/layers/absval_layer.cpp \
   $$PWD/src/caffe/layers/absval_layer.cu \
   $$PWD/src/caffe/layers/accuracy_layer.cpp \
   $$PWD/src/caffe/layers/accuracy_layer.cu \
   $$PWD/src/caffe/layers/argmax_layer.cpp \
   $$PWD/src/caffe/layers/base_conv_layer.cpp \
   $$PWD/src/caffe/layers/base_data_layer.cpp \
   $$PWD/src/caffe/layers/base_data_layer.cu \
   $$PWD/src/caffe/layers/batch_norm_layer.cpp \
   $$PWD/src/caffe/layers/batch_norm_layer.cu \
   $$PWD/src/caffe/layers/batch_reindex_layer.cpp \
   $$PWD/src/caffe/layers/batch_reindex_layer.cu \
   $$PWD/src/caffe/layers/bias_layer.cpp \
   $$PWD/src/caffe/layers/bias_layer.cu \
   $$PWD/src/caffe/layers/bnll_layer.cpp \
   $$PWD/src/caffe/layers/bnll_layer.cu \
   $$PWD/src/caffe/layers/clip_layer.cpp \
   $$PWD/src/caffe/layers/clip_layer.cu \
   $$PWD/src/caffe/layers/concat_layer.cpp \
   $$PWD/src/caffe/layers/concat_layer.cu \
   $$PWD/src/caffe/layers/contrastive_loss_layer.cpp \
   $$PWD/src/caffe/layers/contrastive_loss_layer.cu \
   $$PWD/src/caffe/layers/conv_layer.cpp \
   $$PWD/src/caffe/layers/conv_layer.cu \
   $$PWD/src/caffe/layers/crop_layer.cpp \
   $$PWD/src/caffe/layers/crop_layer.cu \
   $$PWD/src/caffe/layers/cudnn_conv_layer.cpp \
   $$PWD/src/caffe/layers/cudnn_conv_layer.cu \
   $$PWD/src/caffe/layers/cudnn_deconv_layer.cpp \
   $$PWD/src/caffe/layers/cudnn_deconv_layer.cu \
   $$PWD/src/caffe/layers/cudnn_lcn_layer.cpp \
   $$PWD/src/caffe/layers/cudnn_lcn_layer.cu \
   $$PWD/src/caffe/layers/cudnn_lrn_layer.cpp \
   $$PWD/src/caffe/layers/cudnn_lrn_layer.cu \
   $$PWD/src/caffe/layers/cudnn_pooling_layer.cpp \
   $$PWD/src/caffe/layers/cudnn_pooling_layer.cu \
   $$PWD/src/caffe/layers/cudnn_relu_layer.cpp \
   $$PWD/src/caffe/layers/cudnn_relu_layer.cu \
   $$PWD/src/caffe/layers/cudnn_sigmoid_layer.cpp \
   $$PWD/src/caffe/layers/cudnn_sigmoid_layer.cu \
   $$PWD/src/caffe/layers/cudnn_softmax_layer.cpp \
   $$PWD/src/caffe/layers/cudnn_softmax_layer.cu \
   $$PWD/src/caffe/layers/cudnn_tanh_layer.cpp \
   $$PWD/src/caffe/layers/cudnn_tanh_layer.cu \
   $$PWD/src/caffe/layers/data_layer.cpp \
   $$PWD/src/caffe/layers/deconv_layer.cpp \
   $$PWD/src/caffe/layers/deconv_layer.cu \
   $$PWD/src/caffe/layers/dropout_layer.cpp \
   $$PWD/src/caffe/layers/dropout_layer.cu \
   $$PWD/src/caffe/layers/dummy_data_layer.cpp \
   $$PWD/src/caffe/layers/eltwise_layer.cpp \
   $$PWD/src/caffe/layers/eltwise_layer.cu \
   $$PWD/src/caffe/layers/elu_layer.cpp \
   $$PWD/src/caffe/layers/elu_layer.cu \
   $$PWD/src/caffe/layers/embed_layer.cpp \
   $$PWD/src/caffe/layers/embed_layer.cu \
   $$PWD/src/caffe/layers/euclidean_loss_layer.cpp \
   $$PWD/src/caffe/layers/euclidean_loss_layer.cu \
   $$PWD/src/caffe/layers/exp_layer.cpp \
   $$PWD/src/caffe/layers/exp_layer.cu \
   $$PWD/src/caffe/layers/filter_layer.cpp \
   $$PWD/src/caffe/layers/filter_layer.cu \
   $$PWD/src/caffe/layers/flatten_layer.cpp \
   $$PWD/src/caffe/layers/hdf5_data_layer.cpp \
   $$PWD/src/caffe/layers/hdf5_data_layer.cu \
   $$PWD/src/caffe/layers/hdf5_output_layer.cpp \
   $$PWD/src/caffe/layers/hdf5_output_layer.cu \
   $$PWD/src/caffe/layers/hinge_loss_layer.cpp \
   $$PWD/src/caffe/layers/im2col_layer.cpp \
   $$PWD/src/caffe/layers/im2col_layer.cu \
   $$PWD/src/caffe/layers/image_data_layer.cpp \
   $$PWD/src/caffe/layers/infogain_loss_layer.cpp \
   $$PWD/src/caffe/layers/inner_product_layer.cpp \
   $$PWD/src/caffe/layers/inner_product_layer.cu \
   $$PWD/src/caffe/layers/input_layer.cpp \
   $$PWD/src/caffe/layers/log_layer.cpp \
   $$PWD/src/caffe/layers/log_layer.cu \
   $$PWD/src/caffe/layers/loss_layer.cpp \
   $$PWD/src/caffe/layers/lrn_layer.cpp \
   $$PWD/src/caffe/layers/lrn_layer.cu \
   $$PWD/src/caffe/layers/lstm_layer.cpp \
   $$PWD/src/caffe/layers/lstm_unit_layer.cpp \
   $$PWD/src/caffe/layers/lstm_unit_layer.cu \
   $$PWD/src/caffe/layers/memory_data_layer.cpp \
   $$PWD/src/caffe/layers/multinomial_logistic_loss_layer.cpp \
   $$PWD/src/caffe/layers/mvn_layer.cpp \
   $$PWD/src/caffe/layers/mvn_layer.cu \
   $$PWD/src/caffe/layers/neuron_layer.cpp \
   $$PWD/src/caffe/layers/parameter_layer.cpp \
   $$PWD/src/caffe/layers/pooling_layer.cpp \
   $$PWD/src/caffe/layers/pooling_layer.cu \
   $$PWD/src/caffe/layers/power_layer.cpp \
   $$PWD/src/caffe/layers/power_layer.cu \
   $$PWD/src/caffe/layers/prelu_layer.cpp \
   $$PWD/src/caffe/layers/prelu_layer.cu \
   $$PWD/src/caffe/layers/recurrent_layer.cpp \
   $$PWD/src/caffe/layers/recurrent_layer.cu \
   $$PWD/src/caffe/layers/reduction_layer.cpp \
   $$PWD/src/caffe/layers/reduction_layer.cu \
   $$PWD/src/caffe/layers/relu_layer.cpp \
   $$PWD/src/caffe/layers/relu_layer.cu \
   $$PWD/src/caffe/layers/reshape_layer.cpp \
   $$PWD/src/caffe/layers/rnn_layer.cpp \
   $$PWD/src/caffe/layers/scale_layer.cpp \
   $$PWD/src/caffe/layers/scale_layer.cu \
   $$PWD/src/caffe/layers/sigmoid_cross_entropy_loss_layer.cpp \
   $$PWD/src/caffe/layers/sigmoid_cross_entropy_loss_layer.cu \
   $$PWD/src/caffe/layers/sigmoid_layer.cpp \
   $$PWD/src/caffe/layers/sigmoid_layer.cu \
   $$PWD/src/caffe/layers/silence_layer.cpp \
   $$PWD/src/caffe/layers/silence_layer.cu \
   $$PWD/src/caffe/layers/slice_layer.cpp \
   $$PWD/src/caffe/layers/slice_layer.cu \
   $$PWD/src/caffe/layers/softmax_layer.cpp \
   $$PWD/src/caffe/layers/softmax_layer.cu \
   $$PWD/src/caffe/layers/softmax_loss_layer.cpp \
   $$PWD/src/caffe/layers/softmax_loss_layer.cu \
   $$PWD/src/caffe/layers/split_layer.cpp \
   $$PWD/src/caffe/layers/split_layer.cu \
   $$PWD/src/caffe/layers/spp_layer.cpp \
   $$PWD/src/caffe/layers/swish_layer.cpp \
   $$PWD/src/caffe/layers/swish_layer.cu \
   $$PWD/src/caffe/layers/tanh_layer.cpp \
   $$PWD/src/caffe/layers/tanh_layer.cu \
   $$PWD/src/caffe/layers/threshold_layer.cpp \
   $$PWD/src/caffe/layers/threshold_layer.cu \
   $$PWD/src/caffe/layers/tile_layer.cpp \
   $$PWD/src/caffe/layers/tile_layer.cu \
   $$PWD/src/caffe/layers/window_data_layer.cpp \
   $$PWD/src/caffe/proto/caffe.proto \
   $$PWD/src/caffe/solvers/adadelta_solver.cpp \
   $$PWD/src/caffe/solvers/adadelta_solver.cu \
   $$PWD/src/caffe/solvers/adagrad_solver.cpp \
   $$PWD/src/caffe/solvers/adagrad_solver.cu \
   $$PWD/src/caffe/solvers/adam_solver.cpp \
   $$PWD/src/caffe/solvers/adam_solver.cu \
   $$PWD/src/caffe/solvers/nesterov_solver.cpp \
   $$PWD/src/caffe/solvers/nesterov_solver.cu \
   $$PWD/src/caffe/solvers/rmsprop_solver.cpp \
   $$PWD/src/caffe/solvers/rmsprop_solver.cu \
   $$PWD/src/caffe/solvers/sgd_solver.cpp \
   $$PWD/src/caffe/solvers/sgd_solver.cu \
   $$PWD/src/caffe/test/test_data/generate_sample_data.py \
   $$PWD/src/caffe/test/test_data/sample_data.h5 \
   $$PWD/src/caffe/test/test_data/sample_data_2_gzip.h5 \
   $$PWD/src/caffe/test/test_data/sample_data_list.txt \
   $$PWD/src/caffe/test/test_data/solver_data.h5 \
   $$PWD/src/caffe/test/test_data/solver_data_list.txt \
   $$PWD/src/caffe/test/CMakeLists.txt \
   $$PWD/src/caffe/test/test_accuracy_layer.cpp \
   $$PWD/src/caffe/test/test_argmax_layer.cpp \
   $$PWD/src/caffe/test/test_batch_norm_layer.cpp \
   $$PWD/src/caffe/test/test_batch_reindex_layer.cpp \
   $$PWD/src/caffe/test/test_benchmark.cpp \
   $$PWD/src/caffe/test/test_bias_layer.cpp \
   $$PWD/src/caffe/test/test_blob.cpp \
   $$PWD/src/caffe/test/test_caffe_main.cpp \
   $$PWD/src/caffe/test/test_common.cpp \
   $$PWD/src/caffe/test/test_concat_layer.cpp \
   $$PWD/src/caffe/test/test_contrastive_loss_layer.cpp \
   $$PWD/src/caffe/test/test_convolution_layer.cpp \
   $$PWD/src/caffe/test/test_crop_layer.cpp \
   $$PWD/src/caffe/test/test_data_layer.cpp \
   $$PWD/src/caffe/test/test_data_transformer.cpp \
   $$PWD/src/caffe/test/test_db.cpp \
   $$PWD/src/caffe/test/test_deconvolution_layer.cpp \
   $$PWD/src/caffe/test/test_dummy_data_layer.cpp \
   $$PWD/src/caffe/test/test_eltwise_layer.cpp \
   $$PWD/src/caffe/test/test_embed_layer.cpp \
   $$PWD/src/caffe/test/test_euclidean_loss_layer.cpp \
   $$PWD/src/caffe/test/test_filler.cpp \
   $$PWD/src/caffe/test/test_filter_layer.cpp \
   $$PWD/src/caffe/test/test_flatten_layer.cpp \
   $$PWD/src/caffe/test/test_gradient_based_solver.cpp \
   $$PWD/src/caffe/test/test_hdf5_output_layer.cpp \
   $$PWD/src/caffe/test/test_hdf5data_layer.cpp \
   $$PWD/src/caffe/test/test_hinge_loss_layer.cpp \
   $$PWD/src/caffe/test/test_im2col_kernel.cu \
   $$PWD/src/caffe/test/test_im2col_layer.cpp \
   $$PWD/src/caffe/test/test_image_data_layer.cpp \
   $$PWD/src/caffe/test/test_infogain_loss_layer.cpp \
   $$PWD/src/caffe/test/test_inner_product_layer.cpp \
   $$PWD/src/caffe/test/test_internal_thread.cpp \
   $$PWD/src/caffe/test/test_io.cpp \
   $$PWD/src/caffe/test/test_layer_factory.cpp \
   $$PWD/src/caffe/test/test_lrn_layer.cpp \
   $$PWD/src/caffe/test/test_lstm_layer.cpp \
   $$PWD/src/caffe/test/test_math_functions.cpp \
   $$PWD/src/caffe/test/test_maxpool_dropout_layers.cpp \
   $$PWD/src/caffe/test/test_memory_data_layer.cpp \
   $$PWD/src/caffe/test/test_multinomial_logistic_loss_layer.cpp \
   $$PWD/src/caffe/test/test_mvn_layer.cpp \
   $$PWD/src/caffe/test/test_net.cpp \
   $$PWD/src/caffe/test/test_neuron_layer.cpp \
   $$PWD/src/caffe/test/test_platform.cpp \
   $$PWD/src/caffe/test/test_pooling_layer.cpp \
   $$PWD/src/caffe/test/test_power_layer.cpp \
   $$PWD/src/caffe/test/test_protobuf.cpp \
   $$PWD/src/caffe/test/test_random_number_generator.cpp \
   $$PWD/src/caffe/test/test_reduction_layer.cpp \
   $$PWD/src/caffe/test/test_reshape_layer.cpp \
   $$PWD/src/caffe/test/test_rnn_layer.cpp \
   $$PWD/src/caffe/test/test_scale_layer.cpp \
   $$PWD/src/caffe/test/test_sigmoid_cross_entropy_loss_layer.cpp \
   $$PWD/src/caffe/test/test_slice_layer.cpp \
   $$PWD/src/caffe/test/test_softmax_layer.cpp \
   $$PWD/src/caffe/test/test_softmax_with_loss_layer.cpp \
   $$PWD/src/caffe/test/test_solver.cpp \
   $$PWD/src/caffe/test/test_solver_factory.cpp \
   $$PWD/src/caffe/test/test_split_layer.cpp \
   $$PWD/src/caffe/test/test_spp_layer.cpp \
   $$PWD/src/caffe/test/test_stochastic_pooling.cpp \
   $$PWD/src/caffe/test/test_syncedmem.cpp \
   $$PWD/src/caffe/test/test_tanh_layer.cpp \
   $$PWD/src/caffe/test/test_threshold_layer.cpp \
   $$PWD/src/caffe/test/test_tile_layer.cpp \
   $$PWD/src/caffe/test/test_upgrade_proto.cpp \
   $$PWD/src/caffe/test/test_util_blas.cpp \
   $$PWD/src/caffe/util/benchmark.cpp \
   $$PWD/src/caffe/util/blocking_queue.cpp \
   $$PWD/src/caffe/util/cudnn.cpp \
   $$PWD/src/caffe/util/db.cpp \
   $$PWD/src/caffe/util/db_leveldb.cpp \
   $$PWD/src/caffe/util/db_lmdb.cpp \
   $$PWD/src/caffe/util/hdf5.cpp \
   $$PWD/src/caffe/util/im2col.cpp \
   $$PWD/src/caffe/util/im2col.cu \
   $$PWD/src/caffe/util/insert_splits.cpp \
   $$PWD/src/caffe/util/io.cpp \
   $$PWD/src/caffe/util/math_functions.cpp \
   $$PWD/src/caffe/util/math_functions.cu \
   $$PWD/src/caffe/util/signal_handler.cpp \
   $$PWD/src/caffe/util/upgrade_proto.cpp \
   $$PWD/src/caffe/blob.cpp \
   $$PWD/src/caffe/CMakeLists.txt \
   $$PWD/src/caffe/common.cpp \
   $$PWD/src/caffe/data_transformer.cpp \
   $$PWD/src/caffe/internal_thread.cpp \
   $$PWD/src/caffe/layer.cpp \
   $$PWD/src/caffe/layer_factory.cpp \
   $$PWD/src/caffe/net.cpp \
   $$PWD/src/caffe/parallel.cpp \
   $$PWD/src/caffe/solver.cpp \
   $$PWD/src/caffe/syncedmem.cpp \
   $$PWD/src/gtest/CMakeLists.txt \
   $$PWD/src/gtest/gtest-all.cpp \
   $$PWD/src/gtest/gtest_main.cc \
   $$PWD/tools/extra/extract_seconds.py \
   $$PWD/tools/extra/launch_resize_and_crop_images.sh \
   $$PWD/tools/extra/parse_log.py \
   $$PWD/tools/extra/parse_log.sh \
   $$PWD/tools/extra/plot_log.gnuplot.example \
   $$PWD/tools/extra/plot_training_log.py.example \
   $$PWD/tools/extra/resize_and_crop_images.py \
   $$PWD/tools/extra/summarize.py \
   $$PWD/tools/caffe.cpp \
   $$PWD/tools/CMakeLists.txt \
   $$PWD/tools/compute_image_mean.cpp \
   $$PWD/tools/convert_imageset.cpp \
   $$PWD/tools/extract_features.cpp \
   $$PWD/tools/upgrade_net_proto_binary.cpp \
   $$PWD/tools/upgrade_net_proto_text.cpp \
   $$PWD/tools/upgrade_solver_proto_text.cpp

INCLUDEPATH = \
    $$PWD/include/caffe/proto \
    $$PWD/include/caffe/util \
    $$PWD/include \
    $$PWD/src/gtest
#set opencv
OPENCV_INCLUDE_PATH=/usr/local/include
INCLUDEPATH += $$OPENCV_INCLUDE_PATH/opencv \
               $$$OPENCV_INCLUDE_PATH/opencv2
OPENCV_LIB_PATH=/usr/local/lib
LIBS+= -L $$OPENCV_LIB_PATH
LIBS+= \
     -lopencv_aruco.so \
     -lopencv_bgsegm.so \
     -lopencv_bioinspired.so \
     -lopencv_calib3d.so \
     -lopencv_ccalib.so \
     -lopencv_core.so \
     -lopencv_datasets.so \
     -lopencv_dnn.so \
     -lopencv_dpm.so \
     -lopencv_face.so \
     -lopencv_features2d.so \
     -lopencv_flann.so \
     -lopencv_freetype.so \
     -lopencv_fuzzy.so \
     -lopencv_highgui.so \
     -lopencv_imgcodecs.so \
     -lopencv_imgproc.so \
     -lopencv_ml.so \
     -lopencv_objdetect.so \
     -lopencv_optflow.so \
     -lopencv_phase_unwrapping.so \
     -lopencv_photo.so \
     -lopencv_plot.so \
     -lopencv_reg.so \
     -lopencv_rgbd.so \
     -lopencv_saliency.so \
     -lopencv_shape.so \
     -lopencv_stereo.so \
     -lopencv_stitching.so \
     -lopencv_structured_light.so \
     -lopencv_superres.so \
     -lopencv_surface_matching.so \
     -lopencv_text.so \
     -lopencv_tracking.so \
     -lopencv_video.so \
     -lopencv_videoio.so \
     -lopencv_videostab.so \
     -lopencv_xfeatures2d.so \
     -lopencv_ximgproc.so \
     -lopencv_xobjdetect.so \
     -lopencv_xphoto.so \

#set caffe
#$CAFFE_PATH=/home/wangpengcheng/caffe/caffe/
#LIBS += -L $$CAFFE_PATH/build/lib
#LIBS += -lcaffe
LIBS += -lglog -lgflags -lprotobuf -lboost_system -lboost_thread -llmdb -lleveldb -lstdc++  -lcblas -latlas -lpthread
#set cuda
CUDA_PATH=/usr/local/cuda

INCLUDEPATH += $$CUDA_PATH/include \
               $$CUDA_PATH/bin

LIBS += -L $$CUDA_PATH/lib64
LIBS += -lcudart -lcublas -lcurand

#DEFINES = 

